package com.peknight.codec.circe.derivation

trait DecodingFailureMigrationInstances:
  given DecodingFailureMigration = DecodingFailureMigration
end DecodingFailureMigrationInstances
object DecodingFailureMigrationInstances extends DecodingFailureMigrationInstances
