package com.peknight.codec.circe.instances

import com.peknight.codec.circe.error.DecodingFailureMigration

trait DecodingFailureMigrationInstances:
  given DecodingFailureMigration = DecodingFailureMigration
end DecodingFailureMigrationInstances
object DecodingFailureMigrationInstances extends DecodingFailureMigrationInstances
